# Generated by Django 4.2.13 on 2025-10-17 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('date', models.DateField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('total_activities', models.IntegerField(default=0)),
                ('create_count', models.IntegerField(default=0)),
                ('update_count', models.IntegerField(default=0)),
                ('delete_count', models.IntegerField(default=0)),
                ('upload_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('transcribe_count', models.IntegerField(default=0)),
                ('login_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities_activitysummary',
                'indexes': [models.Index(fields=['period', 'date'], name='activities__period_b56a24_idx'), models.Index(fields=['user', 'period', 'date'], name='activities__user_id_b0d605_idx')],
                'unique_together': {('period', 'date', 'hour', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('download', 'Download'), ('transcribe', 'Transcribe'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'View'), ('search', 'Search'), ('export', 'Export'), ('import', 'Import'), ('schedule', 'Schedule'), ('run', 'Run'), ('pause', 'Pause'), ('resume', 'Resume'), ('cancel', 'Cancel'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities_activity',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='activities__user_id_3cda68_idx'), models.Index(fields=['action', 'timestamp'], name='activities__action_1a6547_idx'), models.Index(fields=['level', 'timestamp'], name='activities__level_b00112_idx'), models.Index(fields=['content_type', 'object_id'], name='activities__content_32e159_idx')],
            },
        ),
    ]
