# Generated by Django 5.2 on 2025-10-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('time', models.TimeField(default='09:00', help_text='执行时间，格式: HH:MM')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='每周执行的日期 [0-6]，0=周日')),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='包含 language, model, auto_process 等配置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='最后一次执行时间', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='下次执行时间', null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler_schedule',
            },
        ),
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='执行时间')),
                ('duration', models.FloatField(blank=True, help_text='执行耗时(秒)', null=True)),
                ('jobs_created', models.IntegerField(default=0, help_text='本次创建的任务数')),
                ('error_message', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scheduler.schedule')),
            ],
            options={
                'db_table': 'scheduler_schedulerun',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_active', 'next_run'], name='scheduler_s_is_acti_cb3541_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_type', 'is_active'], name='scheduler_s_schedul_ed9ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['created_by', 'is_active'], name='scheduler_s_created_8206dd_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerun',
            index=models.Index(fields=['schedule', 'status'], name='scheduler_s_schedul_c7414c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerun',
            index=models.Index(fields=['timestamp'], name='scheduler_s_timesta_e18b7a_idx'),
        ),
    ]
