# Generated by Django 4.2.13 on 2025-10-17 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('transcription', 'Transcription'), ('cleanup', 'Cleanup'), ('backup', 'Backup'), ('import', 'Import')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20)),
                ('cron_expression', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('log_output', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scheduler.schedule')),
            ],
            options={
                'db_table': 'scheduler_schedulerun',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['schedule', 'status'], name='scheduler_s_schedul_c7414c_idx'), models.Index(fields=['started_at'], name='scheduler_s_started_517d8b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status', 'next_run'], name='scheduler_s_status_60f6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['type', 'status'], name='scheduler_s_type_e2db35_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['created_by', 'status'], name='scheduler_s_created_1e66ed_idx'),
        ),
    ]
