# Generated by Django 4.2.13 on 2025-10-16 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed')], db_index=True, default='unreviewed', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='文本摘要(前200字)')),
                ('char_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
                'db_table': 'transcripts_transcript',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.IntegerField()),
                ('content', models.TextField(help_text='完整转录文本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(help_text='编辑此版本的用户', on_delete=django.db.models.deletion.CASCADE, related_name='edited_versions', to=settings.AUTH_USER_MODEL)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='transcripts.transcript')),
            ],
            options={
                'verbose_name': 'Transcript Version',
                'verbose_name_plural': 'Transcript Versions',
                'db_table': 'transcripts_transcriptversion',
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddField(
            model_name='transcript',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transcripts.transcriptversion'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='media.mediafile'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='owner',
            field=models.ForeignKey(help_text='首次生成转录的用户', on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transcriptversion',
            index=models.Index(fields=['transcript', '-version_no'], name='transcripts_transcr_fd334a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transcriptversion',
            unique_together={('transcript', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['owner', 'qc_status'], name='transcripts_owner_i_5b2f47_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['-updated_at'], name='transcripts_updated_f5f398_idx'),
        ),
    ]
