# Generated by Django 4.2.13 on 2025-10-17 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('transcription', 'Transcription'), ('storage', 'Storage'), ('system', 'System'), ('notification', 'Notification')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('default_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_systemsetting',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category', 'is_public'], name='settings_sy_categor_2acdf5_idx'), models.Index(fields=['key'], name='settings_sy_key_d49ddf_idx')],
            },
        ),
    ]
