# Generated by Django 4.2.13 on 2025-10-16 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('signup', 'User Signup'), ('signin', 'User Sign In'), ('signout', 'User Sign Out'), ('upload', 'File Upload'), ('import', 'File Import'), ('transcribe', 'Start Transcription'), ('edit', 'Edit Transcript'), ('rollback', 'Rollback Version'), ('mark_qc', 'Mark QC Status'), ('delete', 'Delete Resource'), ('update_tags', 'Update Tags'), ('retry_job', 'Retry Job'), ('cancel_job', 'Cancel Job'), ('update_settings', 'Update Settings'), ('scheduler_run', 'Scheduler Run'), ('nas_scan', 'NAS Scan'), ('export', 'Export Data')], db_index=True, max_length=30)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='操作详情(JSON 格式)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='操作者(System 为 null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'audit_activitylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_activ_actor_i_1f8acb_idx'), models.Index(fields=['event', '-created_at'], name='audit_activ_event_5a2fb5_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_activ_target__7cc2a7_idx')],
            },
        ),
    ]
